FROM resin/rpi-debian

RUN apt-get update && apt-get install -y samba
COPY *.txt /
RUN echo 'password' | tee - | smbpasswd -sa root && \
  # Make directory to share
  mkdir /data && \
  # Adjust Samba configuration
  cat smb.txt >> /etc/samba/smb.conf && \
  # Stop Samba
  service smbd stop && \
  # Clean up
  rm *.txt

# Run Samba in the foreground
CMD ["/usr/sbin/smbd", "-FS"]