version: '2'
services:
  nuxt:
    build: ./frontend
    expose:
      - "80"
  proxy:
    build: ./haproxy
    depends_on:
      - nuxt
      - server
    ports:
      - "80:80"

  server:
    build: ./server
    expose:
      - "9010"