version: '2'
volumes:
    songs:
services:
  nuxt:
    build: ./frontend
    expose:
      - "3000"

  proxy:
    build: ./haproxy
    depends_on:
      - nuxt
      - server
    ports:
      - "80:80"

  server:
    build: ./server
    expose:
      - "9010"
    volumes:
      - 'songs:/usr/src/app/songs'

  samba:
    build: ./samba
    restart: unless-stopped
    volumes:
      - 'songs:/data'
    ports:
    - "137:137"
    - "138:138"
    - "139:139"
    - "445:445"