version: '2'
volumes:
    songs:
services:
  nuxt:
    build: ./frontend
    expose:
      - "3000"

  proxy:
    build: ./haproxy
    depends_on:
      - nuxt
      - server
    ports:
      - "80:80"

  server:
    build: ./server
    expose:
      - "9010"
    volumes:
      - 'songs:/usr/src/app/songs'

  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - 'songs:/mnt'
    command: '-s "Mount;/mnt"'