version: '2'
services:
  nuxt:
    build: ./frontend
    expose:
      - "80"
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - server
      - nuxt

  server:
    build: ./server
    expose:
      - "9010"