version: '2'
services:
  nuxt:
    build: ./frontend
    expose:
      - "80"
  nginx:
    restart: always
    image: nginx:1.13.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - server
      - nuxt

  server:
    build: ./server
    expose:
      - "9010"