FROM resin/%%RESIN_MACHINE_NAME%%-node:9-slim

# Defines our working directory in container
WORKDIR /usr/src/app

COPY package.json package.json

RUN JOBS=MAX npm install --production
COPY . ./

# server.js will run when container starts up on the device
CMD ["npm", "start"]